# Generated by Django 6.1.1 on 2026-09-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('service', models.CharField(choices=[('Website & Software Development', 'Website & Software Development'), ('Online Applications & Digital Services', 'Online Applications & Digital Services'), ('Company Registration & Business Compliance', 'Company Registration & Business Compliance'), ('Graphic Design, Branding & Printing', 'Graphic Design, Branding & Printing'), ('Digital Marketing & Social Media', 'Digital Marketing & Social Media'), ('Business Consultancy & Development', 'Business Consultancy & Development'), ('Technology & Digital Solutions', 'Technology & Digital Solutions')], max_length=100)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
